url: https://savoir-vivre-eco.github.io
baseurl: /ada-impact/

# Site settings
title: +Impact
email: ada-impact@gmail.com
description: "ADA Impact is a Purposeful Cardano Stake Pool that invests in the Future by tackling global issues like polution, climate change, food security and equal education."


# Team names, titles and social links
people:
- name: Cris Pires
  pic: 11
  position: SPO
  social:
    - title:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Twitter
    url: http://twitter.com/jekyllrb
  - title: Telegram
    url:
  - title: Reddit
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: Website
    url: http://bitbucket.org/jekyll


# Postal address (add as many lines as necessary)


# Build settings
markdown: kramdown
permalink: pretty
